# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: workspace on runner
        run: |
          echo github.workspace: ${{ github.workspace }}
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: alpine:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: workspace on container
        run: |
          echo github.workspace: ${{ github.workspace }}
          echo GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}
          echo "/__w/"
          ls -la /__w/
          ls -la /__w/didactic-guacamole/didactic-guacamole
      - name: workspace container-ception
        uses: rsese/test-actions-docker-container@master
        with:
          who-to-greet: ryan-gosling
